spring.application.name=studentsphere-backend

DATABASE_URL=postgresql://studentsphere_db_user:RmwtBHFb5snQ3iBK6OEhugLtnc0qBcp2@dpg-db3gfcui0phs73a33deg-a.oregon-postgres.render.com/studentsphere_db
DATABASE_USERNAME=studentsphere_db_user
DATABASE_PASSWORD=RmwtBHFb5snQ3iBK6OEhugLtnc0qBcp2

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:5432}

jwt.secret=StudentSphereSecretKeyForJWTAuthentication2026VerySecure

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.fail-on-empty-beans=false

spring.jpa.open-in-view=false
