spring.application.name=studentsphere-backend

# ==============================
# SERVER
# ==============================
server.port=${PORT:8080}

# ==============================
# DATABASE - POSTGRESQL
# ==============================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA / HIBERNATE
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==============================
# JWT
# ==============================
jwt.secret=${JWT_SECRET}

# ==============================
# JACKSON
# ==============================
spring.jackson.serialization.fail-on-empty-beans=false
